/*
	File: fn_varHandle.sqf
	Author: Bryan "Tonic" Boardwine

	Description:
	Master handler for getting a variables name, short name, etc.
*/
private["_var","_mode"];
_var = [_this,0,"",[""]] call BIS_fnc_param;
_mode = [_this,1,-1,[0]] call BIS_fnc_param;
if(_var == "" OR _mode == -1) exitWith {""};

switch (_mode) do
{
	case 0:
	{
		switch (_var) do
		{
			case "oilu": {"life_inv_oilu"};
			case "oilp": {"life_inv_oilp"};
			case "heroinu": {"life_inv_heroinu"};
			case "heroinp": {"life_inv_heroinp"};
			case "cannabis": {"life_inv_cannabis"};
			case "marijuana": {"life_inv_marijuana"};
			case "apple": {"life_inv_apple"};
			case "water": {"life_inv_water"};
			case "rabbit": {"life_inv_rabbit"};
			case "salema": {"life_inv_salema"};
			case "ornate": {"life_inv_ornate"};
			case "mackerel": {"life_inv_mackerel"};
			case "tuna": {"life_inv_tuna"};
			case "mullet": {"life_inv_mullet"};
			case "catshark": {"life_inv_catshark"};
			case "turtle": {"life_inv_turtle"};
			case "fishing": {"life_inv_fishingpoles"};
			case "coffee": {"life_inv_coffee"};
			case "turtlesoup": {"life_inv_turtlesoup"};
			case "donuts": {"life_inv_donuts"};
			case "fuelEmpty": {"life_inv_fuelEmpty"};
			case "fuelFull": {"life_inv_fuelFull"};
			case "money": {"life_cash"};
			case "pickaxe": {"life_inv_pickaxe"};
			case "copperore": {"life_inv_copperore"};
			case "ironore": {"life_inv_ironore"};
			case "iron_r": {"life_inv_ironr"};
			case "copper_r": {"life_inv_copperr"};
			case "salt": {"life_inv_salt"};
			case "salt_r": {"life_inv_saltr"};
			case "sand": {"life_inv_sand"};
			case "glass": {"life_inv_glass"};
			case "tbacon": {"life_inv_tbacon"};
			case "lockpick": {"life_inv_lockpick"};
			case "redgull": {"life_inv_redgull"};
			case "peach": {"life_inv_peach"};
			case "diamond": {"life_inv_diamond"};
			case "diamondc": {"life_inv_diamondr"};
			case "cocaine": {"life_inv_coke"};
			case "cocainep": {"life_inv_cokep"};
			case "spikeStrip": {"life_inv_spikeStrip"};
			case "cement": {"life_inv_cement"};
			case "rock": {"life_inv_rock"};
			case "goldbar": {"life_inv_goldbar"};
			case "blastingcharge": {"life_inv_blastingcharge"};
			case "boltcutter": {"life_inv_boltcutter"};
			case "defusekit": {"life_inv_defusekit"};
			case "storagesmall": {"life_inv_storagesmall"};
			case "storagebig": {"life_inv_storagebig"};
			case "mushroom": {"life_inv_mushroom"};
			case "magicmushroom": {"life_inv_magicmushroom"};
			case "frog": {"life_inv_frog"};
			case "froglsd": {"life_inv_froglsd"};
			//case "mash": {"life_inv_mash"};
			case "bottles": {"life_inv_bottles"};
			//case "bottledshine": {"life_inv_bottledshine"};
			case "bottledwhiskey": {"life_inv_bottledwhiskey"};
			case "bottledbeer": {"life_inv_bottledbeer"};
			case "whiskey": {"life_inv_whiskey"};
			case "beerp": {"life_inv_beerp"};
			//case "rye": {"life_inv_rye"};
			case "hops": {"life_inv_hops"};
			case "methu": {"life_inv_methu"};
			case "phosphorus": {"life_inv_phosphorus"};
			case "meth": {"life_inv_meth"};
			//case "cornmeal": {"life_inv_cornmeal"};
			case "ziptie": {"life_inv_ziptie"};
			case "gpstracker": {"life_inv_gpstraker"};
			case "lumber": {"life_inv_lumber"};
			case "kidney": {"life_inv_kidney"};
			case "scalpel": {"life_inv_scalpel"};
			case "cargobox": {"life_inv_cargobox"};
			case "tobacco": {"life_inv_tobacco"};
			case "grape": {"life_inv_grape"};
			case "wine": {"life_inv_wine"};
			case "bloodbag": {"life_inv_bloodbag"};
			case "defibrillator": {"life_inv_defibrillator"};
			case "wl": {"life_inv_wl"};
			case "crack": {"life_inv_crack"};
			case "goldu": {"life_inv_goldu"};
			case "goldp": {"life_inv_goldp"};
			case "speedbomb": {"life_inv_speedbomb"};
			case "yeast": {"life_inv_yeast"};
			case "corn": {"life_inv_corn"};
			case "sugar": {"life_inv_sugar"};
			case "moonshine": {"life_inv_moonshine"};
			case "dc": {"life_inv_dc"};
			case "ephedra": {"life_inv_ephedra"};
			case "lithium": {"life_inv_lithium"};
			case "pallet": {"life_inv_pallet"};
		};
	};

	case 1:
	{
		switch (_var) do
		{
			case "life_inv_oilu": {"oilu"};
			case "life_inv_oilp": {"oilp"};
			case "life_inv_heroinu": {"heroinu"};
			case "life_inv_heroinp": {"heroinp"};
			case "life_inv_cannabis": {"cannabis"};
			case "life_inv_marijuana": {"marijuana"};
			case "life_inv_apple": {"apple"};
			case "life_inv_water": {"water"};
			case "life_inv_rabbit": {"rabbit"};
			case "life_inv_salema": {"salema"};
			case "life_inv_ornate": {"ornate"};
			case "life_inv_mackerel": {"mackerel"};
			case "life_inv_tuna": {"tuna"};
			case "life_inv_mullet": {"mullet"};
			case "life_inv_catshark": {"catshark"};
			case "life_inv_turtle": {"turtle"};
			case "life_inv_fishingpoles": {"fishing"};
			case "life_inv_coffee": {"coffee"};
			case "life_inv_turtlesoup": {"turtlesoup"};
			case "life_inv_donuts": {"donuts"};
			case "life_inv_fuelEmpty": {"fuelEmpty"};
			case "life_inv_fuelFull": {"fuelFull"};
			case "life_cash": {"money"};
			case "life_inv_pickaxe": {"pickaxe"};
			case "life_inv_copperore": {"copperore"};
			case "life_inv_ironore": {"ironore"};
			case "life_inv_ironr": {"iron_r"};
			case "life_inv_copperr": {"copper_r"};
			case "life_inv_sand": {"sand"};
			case "life_inv_salt": {"salt"};
			case "life_inv_glass": {"glass"};
			case "life_inv_redgull": {"redgull"};
			case "life_inv_lockpick": {"lockpick"};
			case "life_inv_tbacon": {"tbacon"};
			case "life_inv_peach": {"peach"};
			case "life_inv_diamond": {"diamond"};
			case "life_inv_diamondr": {"diamondc"};
			case "life_inv_saltr": {"salt_r"};
			case "life_inv_coke": {"cocaine"};
			case "life_inv_cokep": {"cocainep"};
			case "life_inv_spikeStrip": {"spikeStrip"};
			case "life_inv_cement": {"cement"};
			case "life_inv_rock": {"rock"};
			case "life_inv_goldbar": {"goldbar"};
			case "life_inv_blastingcharge": {"blastingcharge"};
			case "life_inv_boltcutter": {"boltcutter"};
			case "life_inv_defusekit": {"defusekit"};
			case "life_inv_storagesmall": {"storagesmall"};
			case "life_inv_storagebig": {"storagebig"};
			case "life_inv_mushroom": {"mushroom"};
			case "life_inv_magicmushroom": {"magicmushroom"};
			case "life_inv_frog": {"frog"};
			case "life_inv_froglsd": {"froglsd"};
			case "life_inv_mash": {"mash"};
			case "life_inv_bottles": {"bottles"};
			//case "life_inv_bottledshine": {"bottledshine"};
			case "life_inv_bottledwhiskey": {"bottledwhiskey"};
			case "life_inv_bottledbeer": {"bottledbeer"};
			case "life_inv_whiskey": {"whiskey"};
			case "life_inv_beerp": {"beerp"};
			//case "life_inv_rye": {"rye"};
			case "life_inv_hops": {"hops"};
			case "life_inv_methu": {"methu"};
			case "life_inv_phosphorus": {"phosphorus"};
			case "life_inv_meth": {"meth"};
			//case "life_inv_cornmeal": {"cornmeal"};
			case "life_inv_ziptie": {"ziptie"};
			case "life_inv_gpstracker": {"gpstracker"};
			case "life_inv_lumber": {"lumber"};
			case "life_inv_kidney": {"kidney"};
			case "life_inv_scalpel": {"scalpel"};
			case "life_inv_cargobox": {"cargobox"};
			case "life_inv_tobacco": {"tobacco"};
			case "life_inv_grape": {"grape"};
			case "life_inv_wine": {"wine"};
			case "life_inv_bloodbag": {"bloodbag"};
			case "life_inv_defibrillator": {"defibrillator"};
			case "life_inv_wl": {"wl"};
			case "life_inv_crack": {"crack"};
			case "life_inv_goldu": {"goldu"};
			case "life_inv_goldp": {"goldp"};
			case "life_inv_speedbomb": {"speedbomb"};
			case "life_inv_yeast": {"yeast"};
			case "life_inv_corn": {"corn"};
			case "life_inv_sugar": {"sugar"};
			case "life_inv_moonshine": {"moonshine"};
			case "life_inv_dc": {"dc"};
			case "life_inv_ephedra": {"ephedra"};
			case "life_inv_lithium": {"lithium"};
			case "life_inv_pallet": {"pallet"};
		};
	};
};
